name: Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:

#  print-github-event:
#    name: Print GitHub pull request event
#    runs-on: ubuntu-latest
#    steps:
#      - name: Print the event
#        run: |
#          echo "${{ toJSON(github.event.pull_request) }}"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repo
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Get short sha
        id: get_short_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check the things
        run: |
          chmod a+x verify.sh
          ./verify.sh
